language: java
jdk:
- oraclejdk8
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script: mvn test
after_success:
- mvn clean cobertura:cobertura coveralls:report
env:
  global:
    secure: h5d2la+jZh7hwIwrccCFKFtKpSo+/rk07j37S0i2a7nX6k3V7g7N+E3izKyjeE/T1/EmjEPvXZJZtaiyJhbWOLiN/Cff8R1GGSFXZQHUQJodafiu9uIAlhARE5hK/NalfZAiWQFZYjnRImC1q/3RV+rnQSvJA69Re+/+XTFRkiz9JBJaAlm/umzb6JcR3mihD5CrKWHQLfVgC7P4ecrQyipcErf9xdjly3fu+x0bCW2WfmJwmhWj0qOg8IcGK8yJi4NLtPZOdXMWiT8QkerGpzv6ttxkf2dS5KPAccHmYytELBQNfapHE0q1s7oWq/DkjQ14gIxeh+0qEKn0MhBK9CEXIyHztO3GeOtYGJoZc4loAqLKutXy8pIhMKvArbGLmmyDEt/pd5q5pO8Ut5J+o0ZAJ7jUrVNF8agrTSqKdCziKp6HGSHbraU9Cp6sAvmeGEB5RtpS0I7fFGwx0k5RTwMcMf5OSQ+xzm/MqkSSTIkj+OeZFSKTv5EEmPwm9FRKLMjivQVbKuj8r9eqcOg8x02qlozonK7Ye/rtIE2V7qAgRuSgXyeWrxcu8sP5XUOdYhD/42GTwsTbxHqRC3+qhPtc30MeKrlWz83lyU2JtvLrLs/I783RFPp8ZlaM7XhUkAy/cvb1K4nJil9YPi6OrJmryMtJXNy2ImEAwM09f/E=
