spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gen?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2b8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    banner: true

yanger:
  logger:
    app-name: woai
    level: info
    log-home: F:\data\woai
    dynamic-log-package: com.yanger.starter.test,com.yanger.starter.test2
    dynamic-log-enabled: true

  app:
    config-path: D:\yang

thymeleaf:
  prefix: classpath:/view/  #prefix：指定模板所在的目录
  check-template-location: true  #check-tempate-location: 检查模板路径是否存在
  cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
  suffix:  .html
  #encoding: UTF-8
  #content-type: text/html
  mode: HTML5