spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gen?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2b8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    banner: true

yanger:
  logger:
    app-name: woai
    level: info
    log-home: F:\data\woai
    dynamic-log-package: com.yanger.starter.test,com.yanger.starter.test2
    dynamic-log-enabled: true

  app:
    config-path: D:\yang

jetcache:
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      # 序列化器的全局配置. 仅 remote 类型的缓存需要指定, 可选 java , kryo, jackson
      valueEncoder: jackson
      # 序列化器的全局配置. 仅 remote 类型的缓存需要指定, 可选 java , kryo, jackson
      valueDecoder: jackson
      # 连接单机
      uri: redis://123456@192.168.2.72:6379
#  local:
#    default:
#      type: caffeine
#      keyConvertor: fastjson