server:
  port: 8090

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 20MB
  profiles:
    active: dev

yanger:
  token:
    available-time-minute: 60

  mybatis:
    enable:
      log: true


  id:
    provider-type: property

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




