server:
  port: 8090

dubbo:
  cloud:
    subscribed-services: xx-service
  consumer:
    timeout: 30000
    validation: false
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 20MB
  profiles:
    active: dev

yanger:
  token:
    available-time-minute: 60

