server:
  port: 8083

yanger:
  token:
    enable: false
  serialize-enum:
    enable: true
  mybatis:
    enable-log: true
  logger:
    api-log-enabled: true

##logbook配置
logbook:
  filter:
    enabled: true
#  write:
#    level: info #logbook日志输入级别
#  format:
#    style: json #这个值还可以是 http、json等
#
#logging:
#  level:
#    org:
#      zalando:
#        logbook: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    dynamic:
      db1:
        url: jdbc:mysql://localhost:3306/sys?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
      db2:
        url: jdbc:mysql://localhost:3306/sa?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        effect-package: com.yanger.test.dao
      db3:
        url: jdbc:mysql://localhost:3306/www?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        effect-package: com.yanger.test.mapper
        default-enable: true
    dynamic-enable: true
    dynamic-read-write-enable: true
    dynamic-package-enable: true
    dynamic-write:
      url: jdbc:mysql://localhost:3306/sys?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
    dynamic-read:
      url: jdbc:mysql://localhost:3306/sa?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver